# application-oauth.yml

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 26e9c5f60401e5720ae1
            client-secret: 2dfe3d7bb7acbe7c4fa4f54a0d37f0e0778c80d7
            scope: name,email,avatar_url
          google:
            client-id: 960739415731-is7h46ju0gfu8bj8gsu3vskqgvp6fles.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          # 네이버는 spring security가 기본적을 제공해주지 않기 때문에 github, google과 달리 많은 정보를 적어줘야한다.
          naver:
            client-id: p_AdQBZCyU18HoDW21dV
            client-secret: t7n86TWtnn
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

            # application.yml
            spring:
              profiles:
                include: oauth